# Setup
title:               DAVIDE PASINI
tagline:             'blog of a finacial alchemist'
description:         '<span style="color:#ffffff">Sushi-lover</span> and learning junkie working on <span style="color:#ffffff">algorithmic trading</span> and ML for Finance'
url:                 https://davidpasini.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Davide Pasini
  url:               https://github.com/davidpasini
  email:             david.pasini@gmail.com

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: davidpasini
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: jekyllrb
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
