# Setup
title:               DAVIDE PASINI
tagline:             'a journey through finacial alchemy'
description:         '<span style="color:#ffffff">Sushi-lover</span> and learning junkie working on <span style="color:#ffffff">algorithmic trading</span> and ML for Finance'
url:                 https://davidpasini.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Davide Pasini
  url:               https://github.com/davidpasini
  email:             david.pasini@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
